# Generated by Django 3.0.3 on 2020-04-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200428_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_confirmed',
            new_name='is_confirmed',
        ),
    ]
