# Generated by Django 3.0.3 on 2020-04-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200428_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.ImageField(default='/head_img/default.jpg', upload_to='head_img/53e4ea7e-22e3-4b6e-bfce-4a1624aef51a', verbose_name='头像'),
        ),
    ]
