# Generated by Django 3.0.3 on 2020-04-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200428_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='code',
            field=models.CharField(max_length=256, verbose_name='激活码'),
        ),
        migrations.AlterField(
            model_name='confirmstring',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.ImageField(default='/head_img/default.jpg', upload_to='head_img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
    ]
