# Generated by Django 3.0.3 on 2020-04-30 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200429_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('Admin', '管理员'), ('Ordinary', '普通用户')], default='Ordinary'),
        ),
    ]
