# Generated by Django 3.0.3 on 2020-04-30 16:40

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200430_1531'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.MyUserManager()),
            ],
        ),
    ]
