# Generated by Django 3.0.6 on 2020-05-07 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.tools.rand_str, max_length=64, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=10)),
                ('solution', models.TextField()),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Accepted'), (2, 'Time Limit Exceeded'), (3, 'Memory Limit Exceeded'), (4, 'Wrong Answer'), (6, 'Runtime Error'), (7, 'Compile Error'), (8, 'Presentation Error'), (11, 'System Error'), (12, 'Judging')], db_index=True, default=0)),
                ('error_info', models.TextField(default='', max_length=1024)),
                ('statistic_info', jsonfield.fields.JSONField(default=dict)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '提交',
                'verbose_name_plural': '提交',
                'db_table': 'submission',
                'ordering': ['-create_time'],
            },
        ),
    ]
