# Generated by Django 3.0.3 on 2020-05-03 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.tools.rand_str, max_length=64, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=10)),
                ('solution', models.TextField()),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.IntegerField(db_index=True, default=6)),
                ('error_info', jsonfield.fields.JSONField(default=dict)),
                ('statistic_info', jsonfield.fields.JSONField(default=dict)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '提交',
                'verbose_name_plural': '提交',
                'ordering': ['-create_time'],
            },
        ),
    ]
