# Generated by Django 3.0.3 on 2020-04-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-create_time',), 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.TextField(verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
    ]
