# Generated by Django 3.0.3 on 2020-04-29 17:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=jsonfield.fields.JSONField(verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=jsonfield.fields.JSONField(verbose_name='测试样例'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statistic_info',
            field=jsonfield.fields.JSONField(verbose_name='统计信息'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_scores',
            field=jsonfield.fields.JSONField(verbose_name='测试点'),
        ),
    ]
