# Generated by Django 3.0.3 on 2020-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20200429_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
    ]
