# Generated by Django 3.0.3 on 2020-04-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20200429_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='tag',
        ),
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.ManyToManyField(blank=True, db_table='problem_tag_problem', null=True, to='problem.ProblemTag', verbose_name='标签'),
        ),
    ]
