# Generated by Django 3.0.3 on 2020-04-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20200429_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tag',
            field=models.ManyToManyField(blank=True, db_table='problem_tag_problem', null=True, related_name='problems', to='problem.ProblemTag', verbose_name='标签'),
        ),
    ]
