# Generated by Django 3.0.3 on 2020-04-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20200429_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='tag',
            new_name='tags',
        ),
    ]
