# Generated by Django 3.0.3 on 2020-04-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20200429_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['id', 'difficulty'], 'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
    ]
