# Generated by Django 3.0.3 on 2020-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20200430_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='judge_mode',
            field=models.TextField(choices=[('Stardand', '标准'), ('Cumulative', '累加')], default='Stardand', verbose_name='评判模式'),
        ),
    ]
